### PR TITLE
Fixed Select and Checkbox values when set via the initial query

### PR DESCRIPTION
**Pull request by fhafiz**
Both Select and checkbox values were being set to the 1st choice in 'rules' and ignored any values passed in by 'initailQuery'. Added logic to check for 'query.value' to be null. Only then, 'updated_query.value' is changed to 1st choice provided in 'rule'.

### CODE REVIEW

**Comment by dabernathy89** [comment]
Thanks @fhafiz! I'll take a look at this ASAP.

**Comment by dabernathy89** [comment]
Hey @fhafiz give me a shout when you think this is ready to merge. I don't want to merge if you're planning additioanl commits.

**Comment by fhafiz** [comment]
Hi @dabernathy89 , can you review this pull request for me please. Thanks

**Comment by mcinnes01** [comment]
@dabernathy89 any update on getting this merged?

**Comment by dabernathy89** [comment]
Hey! Sorry @fhafiz and @mcinnes01. I have been swamped with planning a conference that's happening in a few weeks. I have a pretty open weekend, however, and will make sure to take a look then!

**Comment by dabernathy89** [comment]
Hey @fhafiz - the core feature has been merged. I made a few changes which you can see in the latest commits on master.

I left the options grouping on the individual `select` rule operator (though tweaked it a bit). I didn't include the same grouping for the actual rules selectors though. I may include that in a future release.

I also didn't include the hiding of the input for `is null` and `is empty`. I like the idea, but since the component is pretty open-ended as to what operands can be used, I want to implement that in a more comprehensive way later. (It's also probably out of the scope of this PR anyway).

Thanks again for your help!

**Pull request merged**
