### PR TITLE
Select input as new ruleType

### PR DESCRIPTION
**Pull request by marksalmon**
Great component, thanks.

I have added a select input because for my use case I wanted to specify a list of options that was too long to use the checkbox or radio options.

### CODE REVIEW

**Comment by dabernathy89** [comment]
Thanks Mark! I'll try to check this out this weekend.

**Comment by paulheijman** [comment]
Hi, Is there any progress on the merge? I really would like to have this option!

**Comment by dabernathy89** [comment]
Sorry to be so slow - just merged! Thanks @marksalmon!

I also added the ability to do a multiple select and made a couple other minor tweaks.

**Comment by paulheijman** [comment]
Thanks!

**Pull request merged**
